---
title: "US News Rankings"
output: html_document
---

```{css, echo=F}
body {
  background-color: #2e2e2e;
  color: bisque;
  font-family: Bitter;
}
@media screen and (prefers-color-scheme: light) {
  body {
    background-color: white;
    color: black;
  }
}
```

```{r setup, include=FALSE}
library(knitr, verbose = F)
opts_chunk$set(echo = F)
```

```{r, include=FALSE, echo=F}
library(dplyr, verbose = F)
library(stringr, verbose = F)
library(kableExtra)
df = read.csv('usnr.csv')
```

```{r echo=F}
df <-
  df %>% mutate(Dept. = ifelse(str_detect(University, 'Statistic'), 'Stat', 'Bstat/Info'),
                .after = 2) %>%
  mutate(University = str_extract(University, '.+?(?= \\()')) %>%
  group_by(Dept.) %>%
  mutate(Dept.Rank = rank(Rank, ties.method = 'min')) %>%
  select(-X) %>% arrange(Rank, Dept.Rank) %>%
  mutate(Results = ifelse(
    (
      str_detect(University,
                 'Pennsylvania State|Purdue|North Carolina State') &
        Dept. == 'Stat'
    ) | (
      str_detect(University,
                 'Emory|Duke|Los Angeles') & Dept. == 'Bstat/Info'
    ),
    'Rej',
    ifelse(
      str_detect(University, 'of Iowa|South Carolina') & Dept. == 'Stat',
      'Acc',
      ifelse(
        (
          str_detect(
            University,
            'Davis|Ohio|Rice|Colorado State|Michigan State|Pitts.|Santa Barbara|Riverside'
          ) & Dept. == 'Stat'
        ) | (
          str_detect(University,
                     'Florida|Chapel') & Dept. == 'Bstat/Info'
        ),
        'Pen',
        ''
      )
    )
  ))
df %>% kbl() %>%
  kable_paper(full_width = F) %>%
  row_spec(1:nrow(df), color = 'gray') %>%
  row_spec((1:nrow(df))[df$Results == 'Pen'], color = 'white') %>%
  row_spec((1:nrow(df))[df$Results == 'Rej'], color = 'red', bold = T) %>%
  row_spec((1:nrow(df))[df$Results == 'Acc'], color = 'green', bold = T)
```