---
title: "US News Rankings"
output: 
  html_document:
    sass: '../../main.scss'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r, include=FALSE, echo=F}
library(dplyr, verbose = F)
library(stringr, verbose = F)
df = read.csv('usnr.csv')
```

## Statistics

```{r echo=F}
df %>% filter(str_detect(University, 'Statistic')) %>%
  arrange(Rank) %>%
  mutate(Stat.Rank = rank(Rank, ties.method = 'min')) %>%
  select(-X) %>%
  mutate(Results = ifelse(
    str_detect(University, 'Pennsylvania State|Purdue|North Carolina State'),
    'R',
    ifelse(
      str_detect(University, 'of Iowa|South Carolina'),
      'A',
      ifelse(
        str_detect(
          University,
          'Davis|Ohio|Rice|Colorado State|Michigan State|Pitts.|Santa Barbara|Riverside'
        ),
        'P',
        ''
      )
    )
  )) %>% knitr::kable(.)
```

## Biostatistics

```{r echo=F}
df %>% filter(str_detect(University, 'Bio.+|Epi.+|Health')) %>%
  arrange(Rank) %>%
  mutate(Stat.Rank = rank(Rank, ties.method = 'min')) %>%
  select(-X) %>%
  mutate(Results = ifelse(
    str_detect(University, 'Chapel|Florida'),
    'P',
    ifelse(str_detect(University, 'Duke|Emory|Angeles'),
           'R',
           '')
  )) %>% knitr::kable(.)
```
